services:
  server_generation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - service_generation

networks:
  service_generation:
    name: network_backend